version: "3.7"
# Default logging options
x-logging:
  &default-logging
  options:
    max-size: '50m'
    max-file: '1'
  driver: json-file

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: advent-backend
    expose:
      - 8000
    environment:
      - TZ=Europe/Berlin
    logging: *default-logging

  calendar-frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    ports:
      - "80:80"
